name: DeployToHeroku

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs: 
  build:
    runs-on: ubuntu-18.04
    if: ${{ github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.9.9 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "mypokedex3456" #Must be unique in Heroku
          heroku_email: "laura.a.byman@gmail.com"
          healthcheck: "https://mypokedex3456.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true