
on:
  # push:
  #   branches:
  #     - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    # if: ${{ github.event_name == 'push' }}
    steps: 
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: '12.x'
        - name: npm install
          run: npm install
        - name: lint
          run: npm run eslint
        - name: build
          run: npm run build
        - name: test
          run: npm run test
        - name: e2e tests
          uses: cypress-io/github-action@v2
          with:
            command: npm run test:e2e
            start: npm run start-prod
            wait-on: http://localhost:5000
        - name: heroku deploy
          uses: akhileshns/heroku-deploy@v3.9.9 # This is the action
          with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: "mypokedex3456" #Must be unique in Heroku
            heroku_email: "laura.a.byman@gmail.com"
            healthcheck: "https://mypokedex3456.herokuapp.com/health"
            checkstring: "ok"
            rollbackonhealthcheckfailed: true
        - name: Bump version and push tag
          if: "!contains(github.event.head_commit.message, '#skip')"
          uses: anothrNick/github-tag-action@1.33.0
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            DEFAULT_BUMP: patch
        - name: notify slack if failure
            uses: 8398a7/action-slack@v3
            with:
            status: ${{ job.status }}
            if_mention: failure
            fields: repo,message,commit,author,action,eventName,ref,workflow # selectable (default: repo,message)
            env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        - name: notify slack if success
            uses: 8398a7/action-slack@v3
            with:
            status: ${{ job.status }}
            if_mention: success
            custom_payload: |
              {
                attachments: [{
                  text: `a new version deployed to https://mypokedex3456.herokuapp.com (${process.env.AS_COMMIT})
                  by ${process.env.AS_AUTHOR}, build took ${process.env.AS_TOOK}`,
                }]
              }
            env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
